### ISSUE TITLE
PQ Respawn Timers

### ISSUE THREAD

**Issue by justinh1984** [smasherprog/EqTool#101]
The automated respawn timers are currently off for Project Quarm. I believe it is using the standard respawn timers not the faster ones for PQ. Also is it possible to allow the CH macro to look for CH - name - 001 in this order as well?

**Comment by smasherprog** [comment]
I can add the CH variation for sure! Ill do that over the next day or 2
the PQ spawn time i need someone else to help. I dont play on PQ to know whats going on there so i need help on thet front

**Comment by justinh1984** [comment]
The CH addition would be great! For the respawn timers of 22 minutes or greater are now all 8 minute and <22 minute are now 6 minute. This may not be correct in all instances however specifically outdoors but it is correct within dungeons in PQ. I think just changing the classic dungeon timers by this method would allow many users to use the respawn triggers you have set up which are very nice. I can try to take a closer look as well and see if I can possibly compile a list from the database.

**Comment by justinh1984** [comment]
I took a look at the Quarm database and got more detailed information on the respawn timers. There is a reducedrespawntimer flag for dungeons only that is currently turned on and that sets spawngroups with varying spawntimers in dungeons to the reduced timers. 
900 - 2400 = 480 (spawns between 15 - 40 min are reduced to 8 minute respawns.
300 - 899 = 360 (spawns between 5 - 14.98 min are reduced to 6 minute respawns.

**Comment by smasherprog** [comment]
Just added support for the chain format
Hanbox shouts, 'CH - name - 001'

**Comment by justinh1984** [comment]
I compiled a debug version that I am testing using the following respawn timers I added to the ZoneParses.cs. I can let you know once I confirm these all to be 100% correct. The CH addition works great thank you!
![image](https://github.com/smasherprog/EqTool/assets/47900844/4964e689-3341-4c99-a7c5-e14bd6bc7a05)

**Comment by smasherprog** [comment]
do a PR.. looks good to me

**Comment by justinh1984** [comment]
Actually the majority of spawns in SK are 36 sec or 360 sec. For example all of the Quillmane placeholders are 36 seconds while stuff like KFC and Gnolls around paw are on the 360 sec timer. I'm not sure what would be more useful as I guess the zone timer would be considered 5 minutes and the Quillmane spawngroup is 36 seconds. Probably the 5 minutes is the more useful and more accurate to the zone description. Ill change that and I want to check a few others to confirm before PR.

**Comment by smasherprog** [comment]
gonna do a PR on this?

**Comment by justinh1984** [comment]
Yes I just put in a PR for this update. I tested most of the dungeons in the list and the 8 minute reduced respawn timer is correct.

**Comment by smasherprog** [comment]
Looks good!

**Comment by smasherprog** [comment]
merged into master
