### ISSUE TITLE
High CPU utilization when logfile is large

### ISSUE THREAD

**Issue by jbwilliams1** [smasherprog/EqTool#102]
If you have a large log file, e.g. dozens of MBs or possibly even hundreds of MBs, eqtool will be both slow to load and will reflect a high CPU utilization in the task manager.

My suggestion to fix this would be to create dot numbered archived logfiles when these files reach a critical mass of, say, 10MB.

**Comment by smasherprog** [comment]
Thanks for reporting this, it was actually a BUSY loop I introduced when i added support for NParse map locations sharing. It is fixed now! 
Should be available to update in about 5 minutes. Let me know if this fixes it

**Comment by jbwilliams1** [comment]
@smasherprog looks good, nice work on eqtool so far. Thanks!
