### ISSUE TITLE
kill timer doesnt trigger when killed by dot on quarm.....not sure if this has been brought up

### ISSUE THREAD

**Issue by UnGodlyWrath** [smasherprog/EqTool#114]
i think its just the trigger it goes by that comes up in chat...."Vhalen Nostrolo has been slan by Jabn!" will pop the trigger and make the timer go...however ive noticed the timer doesnt always trigger....for instance if its killed by a dot from a nec it says "Vhalen Nostrolo died." will not trigger the timer....dunno if that can be added....just thought id mention it....great program tho at any rate!!

**Comment by UnGodlyWrath** [comment]
this is on the quarm version btw sorry forgot that

**Comment by smasherprog** [comment]
Added support for 'King Tormax died.' to supported death triggers

**Comment by smasherprog** [comment]
Should be available to update in about 5 minutes
