### ISSUE TITLE
Only Track My Outgoing Buffs / Debuffs

### ISSUE THREAD

**Issue by alphablueofficial** [smasherprog/EqTool#116]
Is it possible to track only the buffs / debuffs that I cast on others?

When I check 'Spells Me Only' I only see the buffs that I have and not the buffs that I've cast on others.

As a buffing class, this would be very helpful, especially in raids when the Triggers Window can get very cluttered!

I'm on Project Quarm if that is needed. I've seen that another program is able to handle this natively, but I'd much rather PQTools!

**Comment by alphablueofficial** [comment]
I just looked back at previous discussions and saw that this was addressed and a different method was brought up to resolve this! (remove characters / npcs from the triggers list manually)

**Comment by smasherprog** [comment]
It is kinda possible to track only buffs that you cast on others, Typically, you would FILTER the spells that you see by class and this will limit the spells you see.

**Comment by smasherprog** [comment]
I can add this as a future feature
