### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by zelezack** [smasherprog/EqTool#122]
Been working on trying to get this working in linux via Wine and Bottles but the best I can do is get the base application to load. If I try to launch triggers or the map the application crashes. Is there any native Linux support in the works or documentation on dependencies required to get it working in Wine or Bottles.

**Comment by smasherprog** [comment]
I have no idea on that front. I do have a LONG TERM plan to add native support for linux, but its a ways down the road :(

**Comment by alinuxfan** [comment]
@zelezack , what did you do to get rid of the Autofac error? Or did you not have that?
`Unhandled Exception:
System.TypeLoadException: Could not load type of field 'EQTool.App:container' (1) due to: Could not load file or assembly 'Autofac, Version=7.1.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies.
`

**Comment by ryandward** [comment]
> @zelezack , what did you do to get rid of the Autofac error? Or did you not have that? `Unhandled Exception: System.TypeLoadException: Could not load type of field 'EQTool.App:container' (1) due to: Could not load file or assembly 'Autofac, Version=7.1.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. `

Same issue here. I'd love to see how it got fixed.

**Comment by zelezack** [comment]
@ryandward @alinuxfan Was never able to resolve the error. Best I was able to do was load it into Bottles and it would load EQTool into the task bar but when I would select one of the options like Map or Spells it would crash. Gave up messing with it for the time being.

**Comment by alinuxfan** [comment]
Seems to work on Linux right now. Ubuntu 22.04. Automatically found my log files (not in standard folder structure). Going to keep testing

**Comment by smasherprog** [comment]
ohhh damn nice!!! That was a total shot in the dark that i made. Glad to hear it might be working!

**Comment by foleyjohnm** [comment]
Are you guys just downloading the zip and running with wine? Any particular dotnet deps that have to be installed?

**Comment by smasherprog** [comment]
Will have a new deployment for linux on wine heading out soon

**Comment by smasherprog** [comment]
Release deployed, please download a NEW linux version from https://github.com/smasherprog/EqTool/blob/main/README.md

**Comment by smasherprog** [comment]
Let me know if it will now work

**Comment by smasherprog** [comment]
Also, it would be helpfull to move this convo to discord if its not allready there
https://discord.gg/Z6RPUMNcY2

**Comment by smasherprog** [comment]
Linux channel created in discord, lets move this convo there
