### ISSUE TITLE
respawn timers broke this morning

### ISSUE THREAD

**Issue by lanis404** [smasherprog/EqTool#124]
pqtool spawn respawn timers were fine at 8 minutes for dungeons for weeks until this morning when they somehow broke and are showing the wrong time.

**Comment by smasherprog** [comment]
Ill take a look when i get home from work today.

**Comment by smasherprog** [comment]
Can you explain whats happening? What dungeon are you in and what are the timers saying is the respawn?

**Comment by lanis404** [comment]
The issue seems to have fixed itself somehow. Was showing respawn times in guk as 6:30. I deleted the pqtool folder and did a fresh unzip from the latest release and it started showing as 28 minutes as if it was p99. Then I deleted that and restored my original deleted folder and it started working and showing the correct time at 8 minutes again. I have no idea how or why lol

**Comment by lanis404** [comment]
i dunno whats going on but it happened again this morning. it was showing respawn timers for lguk as 8:30 instead of 8 minutes. deleted and redownloaed, now its showing respawn timers as 24 min

**Comment by lanis404** [comment]
ok so i figured out why it was showing respawn as 24 min. i didnt do a / after loading it so that it loads the map for lguk and it thought i was in freeport. the latest version still has lguk respawn time at 8:30 instead of 8 min.  I just reverted to an older version and its showing 8 min respawn again

**Comment by smasherprog** [comment]
Ill take a look later today. I did update the code for PQ spawn timers.

**Comment by smasherprog** [comment]
the 24 min spawn timer issue does make sense. sometimes when logging in you need to do a slash to figure out what zone your in...

**Comment by smasherprog** [comment]
Should be reverted now
