### ISSUE TITLE
Setting to disable autoupdate.

### ISSUE THREAD

**Issue by wsaye** [smasherprog/EqTool#129]
The autoupdate annoyingly minimizes my other applications that I happen to be using (i.e. other multiplayer games!), and it would be nice if there was a setting to disable it, so I don't have to remember to exit out of it every time I log out of EQ. Thanks!

**Comment by smasherprog** [comment]
Just pushed an update so auto update will only happen with your computer is idle for 10 minutes

**Comment by smasherprog** [comment]
reply to this if that doesnt fix the issue please. Gonna close this for now
