### ISSUE TITLE
Quarm Kill Timers

### ISSUE THREAD

**Issue by Celedh** [smasherprog/EqTool#130]
Would it be possible to have an option to have npc spawn timers for quarm?

Is it possible to edit different ncp spawn timers in a file?  Perhaps right click on the npc kill timer in the triggers window and input a different overridden time for that one?

**Comment by Celedh** [comment]
The timers on the docks dorfs in bb had gone from 5 1/2 mins too long to 3 mins too short,  and then in middle of session today went back to 5 1/2 mins too long the way they were in prior days.

**Comment by smasherprog** [comment]
Is this still an issue?

**Comment by Celedh** [comment]
> Is this still an issue?

The dwarf citizens in butcherblock are still 15 minutes where they should be 9.5 minutes, but its much better than when it was 3 mins too short since i can at least see the seconds tick to 5 30 for the spawn.

**Comment by smasherprog** [comment]
Theres a fork off of this which is made for PQ. This might include better support for these differences https://github.com/EJWellman/QuarmTool

**Comment by Celedh** [comment]
Ya, I moved over to that one and he has it fixed for Quarm.  So Long, and Thanks for All the Fish.

**Comment by smasherprog** [comment]
Closing this as i dont support Quarm any more
