### ISSUE TITLE
Ice Giants in Everfrost timer incorrect since last update

### ISSUE THREAD

**Issue by CtrlAltComplete** [smasherprog/EqTool#132]
IG timer in Everfrost is showing 22mins now. It should be 6:40 as before :)

Thanks for this software, its amazing!

**Comment by smasherprog** [comment]
It could be that the program doesnt know what zone you are in. try doing a / in the zone and see if that fixes it. 
The default zone is freeport that pigparse uses if it doesnt know or your last known zone.

**Comment by smasherprog** [comment]
see if that fixes it

**Comment by CtrlAltComplete** [comment]
ohhh that couldve been it! working now! apologies!
