### ISSUE TITLE
App display icon in system tray - thats it

### ISSUE THREAD

**Issue by stf675** [smasherprog/EqTool#14]
App display icon in system tray - thats it
ver 1.0.1.744

When left click or right click or mouse over - nothing.

Only option to close - kill the process.

Any ideas or I am missing something?

**Comment by stf675** [comment]
Update:  when started from same drive where P99 installed it works, but if start from other drive does not.  I assume it trying to scan disk?

**Comment by smasherprog** [comment]
try getting the latest version and see how that works.
