### ISSUE TITLE
outlier pricing not filtered

### ISSUE THREAD

**Issue by princealexi25** [smasherprog/EqTool#16]
I think logic should be integrated that filters out 200% 0r 300% price grabs from average price.  (or at least from reporting until more of the prices show up?)  Outliers make the graphing problematic in some cases.

[https://www.tumblr.com/mattinsd73/713142486236905472](url)

https://www.tumblr.com/mattinsd73/713142486236905472

**Comment by smasherprog** [comment]
I have been going through some of the data to try and remove outliers. This is something i am working on currently.. Most outliers should be removed in the next few days using this method

**Comment by smasherprog** [comment]
I added a scatter chart to each item which will make it easier to see outlier data as well.

**Comment by smasherprog** [comment]
FIXED
