### ISSUE TITLE
Settings get reset

### ISSUE THREAD

**Issue by philmae** [smasherprog/EqTool#17]
Unfortunately, each time the tool starts up, it resets some of my stored settings, like opacity and Windows on top / or not. 
Really annoying

Also, can you add an option that the tool does not close itself automatically after the client crashes (or rebooting the client). So having an option that the tool closes or not depending if the client is closed or not. But starting the tool each time again after you close the client is not helpful.

**Comment by smasherprog** [comment]
Ill check this out when I get home today. Ive never seen it "close" when the client closes.

**Comment by smasherprog** [comment]
what version are you working on?  the lates version is  3.23.330.2

**Comment by philmae** [comment]
Yeah, the latest (isnt this self updating anyways? At least it did for me some time)

What about the settings disappear? Seen that before?

**Comment by philmae** [comment]
So, I tested it a bit today. 
If a random EQTool Window (DPS Meter or Map) is open (selected with checkmark) and client is closed, the tool does not close automatically
If none of the EQTool Windows are open, and the client closes, EQTool closes as well. 
If none of the EQTool Windows are open, and the client is open, EQTool closes as well. 

What I think it should do:
- EQTool should stay open, except I close it specifically. There is no real reason it should close automatically? Or is there? If you missclick a window in EQTool or close the last window accidently.

**Comment by smasherprog** [comment]
thanks for this ill be testing tomorrow and see if i can fix this!

**Comment by smasherprog** [comment]
I was able to use your repro steps to fix this. BIG thanks!
Fix is being built and will be available in 5 minutes

**Comment by smasherprog** [comment]
Going to close this now. Let me know if you have any other issues! Good catch on this BTW
