### ISSUE TITLE
PigParse does not appear to be running

### ISSUE THREAD

**Issue by GreenLegendRan** [smasherprog/EqTool#171]
Issue appears to have started earlier this morning: was working fine last night.  Program seems to lock up on startup.  Only the loot window opens but dies not populate with data.  The zone map window and timer window (mob respawn and spell duration) does not open.  In addition i an getting a pop up indicating that an update is downloading but nothing actually downloads.

**Comment by smasherprog** [comment]
Can you confirm you are on the latest 5.24.121.4 ? 
You can download it from the releases. Simply copy these files over your existing files.

**Comment by GreenLegendRan** [comment]
Yeah I am running 5.24.121.4. The program opens with the Mob Info window
but appears to lock up. The loading icon (spinning blue circle) remains on
the screen for quite some time. When it stops the data in the Mob Info
window is blank and clicking on any of the menu icons at the top of that
window does nothing (accessing the timers, map, etc).

**Comment by GreenLegendRan** [comment]
I got it working again. It looks like something happened when I saved the
new updated files over the old ones. I ended up just deleting the whole
program and reinstalling everything from the latest update instead. That
did the trick.

**Comment by smasherprog** [comment]
glad to hear! not sure what happened!
