### ISSUE TITLE
Ring of Di`zok

### ISSUE THREAD

**Issue by Akamai-Okole** [smasherprog/EqTool#19]
The old Unixgeek used to have problems with spells and such with ' and ` in them. I just noticed that pigparse is not picking up Ring of Di`Zok so it may be having a similar issue. (the symbol under the escape key)

**Comment by smasherprog** [comment]
Yeah this is a problem of tunnel. I posted an issue, but im not sure if is maintained any more.  You should post there! more people will hopefully mean it gets fixed faster.,

https://github.com/jamesjamail/TunnelQuestBot/issues/49

**Comment by rm-you** [comment]
Are you USING tunnelquest's stream as your data source? Actually that's cute, and a pretty good idea honestly, so we only have to maintain one always-online bot. Just didn't realize :P

**Comment by smasherprog** [comment]
I am yes. Dont want to reinvent the wheel
