### ISSUE TITLE
Filter Outlier pricing.  It is affecting averages.  Or ban outliers.

### ISSUE THREAD

**Issue by princealexi25** [smasherprog/EqTool#21]
Or fix your code to detect what is a price and what is not a price.  I don't know what's going on, but it's making the avg price, below material cost for velium ruby veil.  I feel like this user is spike, doping, or /oocing in a bad way that breaks your code detection.

[https://www.tumblr.com/mattinsd73/718231752328593408?source=share](url)

**Comment by smasherprog** [comment]
I am working on this.. I have put some work into it, but its an ongoing issue. Can you paste the picture into the github issue? I have to create an account on that timblr site to view the image.

**Comment by princealexi25** [comment]
![Tumblr_l_126866315001967.jpg](https://github.com/smasherprog/EqTool/assets/4637486/0522c9d8-d992-4c82-8f6a-31766621989d)

**Comment by princealexi25** [comment]
I have a feeling this comes from when people say they have a certain # of items for sale at a price.  The last price aggregator was having issues with this too.  if it's more than 50% or 100% off avg, exclude from calcs?  Game would have to break for such a price drop?

**Comment by smasherprog** [comment]
This is fixed and i added code to prevent more outlier data from getting in

**Comment by smasherprog** [comment]
gonna close for now. Please open if you find more
