### ISSUE TITLE
Map Coords

### ISSUE THREAD

**Issue by someolguy** [smasherprog/EqTool#22]
I noticed when you hover your mouse over the map window, it can display the mouse's coords up on the top right.

It is displaying them in the order of 
Y,X
instead of
X,Y

..reversedd

Very confusing tryna find someone telling me their coords :)

If this is mainly for p99 blue/green, you might want to set the zone respawn timer in Rath Mnts to 6:00 from 6:40

**Comment by smasherprog** [comment]
Above is fixed
