### ISSUE TITLE
Darker UI!

### ISSUE THREAD

**Issue by sKlat-beep** [smasherprog/EqTool#25]
It'd be nice if the UI could be even darker with transparency options and click-through, similar to Nparse. All of the data in the windows is way better than any other tool but them being completely solid takes up a lot of screen real estate.

**Comment by smasherprog** [comment]
which window are you referring to? The only window that can go completely transparent so far is the mob info window, but that was done intentionally as text gets impossible to read.
Or you want the background solid color to be completely black in color?
Or are you just the click through option?

**Comment by smasherprog** [comment]
Dark theme much darker now! check it out. good suggestion!

**Comment by sKlat-beep** [comment]
Love it! Looks great!
