### ISSUE TITLE
Mob Info Screen

### ISSUE THREAD

**Issue by sKlat-beep** [smasherprog/EqTool#26]
Two quick suggestions, add another column for "Vendor Sell Price" for known loot, so we can quickly see trash drop values and add some logic for considering corpses so it's easy to pull up the loot table/wiki link on dead stuff!

**Comment by smasherprog** [comment]
Thats not a bad suggestion. Ill see if I can parse this from the wiki.

**Comment by smasherprog** [comment]
Ill add it to my list to investigate.

**Comment by smasherprog** [comment]
This is too difficult to implement :(

**Comment by sKlat-beep** [comment]
Thanks for looking into it!Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Scott ***@***.***> Date: 12/24/23  10:51 PM  (GMT+01:00) To: smasherprog/EqTool ***@***.***> Cc: sKlat ***@***.***>, Author ***@***.***> Subject: Re: [smasherprog/EqTool] Mob Info Screen (Issue #26) 
This is too difficult to implement :(
