### ISSUE TITLE
Spells/Trigger Window Stopped Tracking after installing a new UI

### ISSUE THREAD

**Issue by SevCorvo** [smasherprog/EqTool#29]
![image](https://github.com/smasherprog/EqTool/assets/141524060/256195ed-19f6-4672-baf3-51146692d8e2)

Checked settings/log file location.  Everything seems to be correct.  It has been updating with my level so it's reading my logs.

The map/DPS/mobinfo parser seems to still work just fine.  Only the spells/triggers window just stopped tracking anything.

**Comment by smasherprog** [comment]
can you post the title of the map window please. It shows the version you are running on

**Comment by SevCorvo** [comment]
Version is:  
![image](https://github.com/smasherprog/EqTool/assets/141524060/9d5fcb71-8563-470f-afc9-1bd074896806)

**Comment by smasherprog** [comment]
Can you check your uifolder for default. This is present, correct ?
<img width="767" alt="image" src="https://github.com/smasherprog/EqTool/assets/3393733/afabda54-ee2e-4bb9-9b19-fcbe80daa76a">

**Comment by smasherprog** [comment]
<img width="707" alt="image" src="https://github.com/smasherprog/EqTool/assets/3393733/3aa41965-3a2e-4ab8-a8e7-b70a3c8f01ff">

**Comment by SevCorvo** [comment]
Yes it is:
![image](https://github.com/smasherprog/EqTool/assets/141524060/e415ae63-3211-4193-a55d-b97d53a44fa0)

**Comment by smasherprog** [comment]
Those need to be in the default folder.. Can you confirm they are?

**Comment by SevCorvo** [comment]
They are not!

**Comment by smasherprog** [comment]
https://www.project1999.com/forums/showthread.php?t=2651
download the getting started zip file. It has the default spell images you can put into the default folder.

**Comment by smasherprog** [comment]
spell images now embedded in program
