### ISSUE TITLE
General suggestions

### ISSUE THREAD

**Issue by Kenshi2358** [smasherprog/EqTool#3]
Hi there. I think this tool is pretty impressive. I like having choices other than nParse. I'm with Drift (names are: Brevil and Runari).
I saw your post on p99 and tried out this tool.

**Typos:**
Dps Meter window --> under 12s DMG --> when highlighting header:
- dealt is spelled "delt"
- gauging is spelled "guaging"

**General suggestions:**
- add option for black background for spells window, dps window, etc.
I'm a big fan of dark mode and makes it easier to see.

- add option to filter active spells by remaining duration left (per target), with spells about to expire at the top.
This makes it easy to know which spells need to be rebuffed next.
Currently the order is in the last spell cast?

- It'd be nice to have a better understanding of when the Dps Meter window of a target disappears after killing a mob.
Maybe could be explained in the readme file? Or added an option to have a lagging 10 seconds before targets disappear?

**The positives:**
- Many more options available in the settings menu compared to nParse.
- Has a dps window - I've never played p99 with one and it's great.
- Pig icon is hilarious.

Overall great job on this. I have a coding background in a few languages, but not C# so it's harder for me to follow everything.

**Comment by smasherprog** [comment]
Fixed the spelling errors. 
I will implement dark theme soon for sure -- Good idea!
The dps window is work in progress. Im still trying to figure out what works best so ive been testing it out alot and making changes. I want it to be useful for groups first then I can create something different for large raids.

Keep the good feedback though! Ill document the DPS window when I get it more finished (the new few days!)

**Comment by smasherprog** [comment]
Just pushed Changes to default sorting of spells as suggested (Good suggestion!)

**Comment by smasherprog** [comment]
Almost have the DPS window flushed out. Still in a separate branch that needs some testing though.
I am working on the dark theme as well.

**Comment by smasherprog** [comment]
Themes are done i just need to test it out. It looks really cool though -- great idea.

**Comment by smasherprog** [comment]
closing this as ive cleaned up everything and it should be good to go now. Let me know if you have any more great suggestions!
