### ISSUE TITLE
Spawn Timers not correct at HHK

### ISSUE THREAD

**Issue by IzHaN80** [smasherprog/EqTool#31]
These are the regular spawn timers ->

Goblins: 10 Minutes
Most Human NPCs: 18 Minutes
4th Floor Guards: 18:40

Then we have a few exceptions here, also noticed you set timer at 9min instead 18min ->

Guard Blayle, Guard Chopin -> 3min Respawn Timer
A noble -> 6min Respawn Timer
Isabella Cellus -> 6min Respawn Timer
Captain Boshinko -> 6min Respawn Timer

Every other Guard and Human alike are on 18min Respawn Timer from 1st to 3rd floor that are not included in this list, this includes Aeris Greymalkyn which lists as 9min respawn timer but in reality is a 18 respawn timer.

I hope this helps you improve your EQTool!

A though also... would i tbe hard to code a way so we users would be able to setup custom timers or alarms? Thanks in advance, keep the good work going!

**Comment by smasherprog** [comment]
Thanks for this info working on the changes now!

**Comment by smasherprog** [comment]
Update released on this it should be correct now.

**Comment by smasherprog** [comment]
There are custom timers but you have to say

start timer  highkeepguard1  6


It will start a timer for 6 minutes

**Comment by smasherprog** [comment]
gonna close this. Let me know if its NOT fixed.  If you find other npcs or incorrect timers, let me know and create another issue.
