### ISSUE TITLE
PQ Support

### ISSUE THREAD

**Issue by sKlat-beep** [smasherprog/EqTool#37]
This app is sick and has quickly replaced NParse for me, any chance we could get support for Project Quarm as well? It doesn't seem to detect the eqgame.exe for the TAKP emu client.

You da best!

**Comment by smasherprog** [comment]
I have to make a seperate version its not hard and something I will do here shortly. Let me see if i can knock it out this weekend

**Comment by smasherprog** [comment]
Im pushing the release now to support Quarm. Still testing.

It will be a separate executable

**Comment by smasherprog** [comment]
PQ SUPPORT DONE.

I left in the MOB window, which pulls from project1999 wiki for now. Not sure what to do with it. Everything else should work as expected.
