### ISSUE TITLE
Program crashing and reloading repeatedly

### ISSUE THREAD

**Issue by TheAngryRogue** [smasherprog/EqTool#38]
Zone: Everfrost peak
Targets: a wooly mammoth, a wooly mammoth calf, a giant wooly spider
Used components: Triggers, Mob Info, map
Class and Abilities used: Druid (27) - Healing, Terrorize Animal, Careless Lightning, Charm Animals, Invisibility Versus, Ensnaring Roots, Snare, Spirit of the Wolf, Gate. //  Hide, Sneak, Tracking, /LOC, Protection of the Glades, 
Additional programs interacting with Everquest: None

Processor	AMD Ryzen 9 3950X 16-Core Processor               3.50 GHz
Installed RAM	64.0 GB
Edition	Windows 10 Home
Version	22H2
Installed on	‎9/‎12/‎2020
OS build	19045.3516
Experience	Windows Feature Experience Pack 1000.19052.1000.0

System updates up to date.

**Comment by smasherprog** [comment]
Download the latest file from https://github.com/smasherprog/EqTool

I apparently broke the AUTO update today for OLDER versions of the program. Ill get that fixed, in the mean time just download the new version and you should be good to go

**Comment by smasherprog** [comment]
making a change that will hopfully fix it for the rest. Thanks for pointing this out!
Let me know if that fixes the problem

**Comment by smasherprog** [comment]
Just tested and the program should auto update correctly now and work as expected without a new download.
