### ISSUE TITLE
Quarm issue showing my buffs on others

### ISSUE THREAD

**Issue by sKlat-beep** [smasherprog/EqTool#40]
This issue only seems to be on Quarm (Thanks for releasing it by the way!!)

When I cast buffs on others or my pets, regardless of the settings for the window, it doesn't show timers for those buffs. It briefly flashes the name of the person/pet I cast on, but it disappears immediately. I tried all sorts of combinations with the settings and still had the same issue, even tried redownloading it just to make sure.

The DPS Meter also doesn't appear to register up DoT Damage

**Comment by smasherprog** [comment]
ill take a look at it tomorrow (10/11) Should be ez

**Comment by smasherprog** [comment]
Can you send me some logs of DOT damage messages please. And the spell your casting on your pet

**Comment by sKlat-beep** [comment]
Sure thing! I'll try to get these over to you tomorrowSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Scott ***@***.***> Date: 10/11/23  9:02 PM  (GMT-06:00) To: smasherprog/EqTool ***@***.***> Cc: sKlat ***@***.***>, Author ***@***.***> Subject: Re: [smasherprog/EqTool] Quarm issue showing my buffs on others (Issue #40) 
Can you send me some logs of DOT damage messages please. And the spell your casting on your pet

**Comment by sKlat-beep** [comment]
[BuffLogs.txt](https://github.com/smasherprog/EqTool/files/12885270/BuffLogs.txt)

Here ya go! Casted Cloud and Quickness on pet, both times the pet name flashes for a second like it registers a buff was received, but it disappears immediately. It looks very similar to what happens on P99 if I deselect other classes or tell it only count the stuff that effects me, but I've messed with those settings and it doesn't change anything.

For the DoTs, The DPS meter just registers the initial 20 damage hit, but not the DoT damage ticks.

**Comment by smasherprog** [comment]
Looks like the spells should show correctly. Please, post a screen shot of your settings. 
Checking on the dps stuff now

**Comment by smasherprog** [comment]
Also in the logs you posted, are there dot damage messages? I dont play on quarm so i only log in to test things and dont have a class that has DOTs to test this out.

**Comment by smasherprog** [comment]
NM I SEE it now.. 
[Thu Oct 12 12:05:15 2023] a goblin warrior has taken 12 damage from your Choke.

**Comment by smasherprog** [comment]
DOT damage support added just now it should auto update soon.

**Comment by smasherprog** [comment]
can you post a pic of your settings? I suspect you might have the checkbow for SHOW ONLY spells that effect me.

**Comment by smasherprog** [comment]
can you post a pic of your settings? I suspect you might have the checkbow for SHOW ONLY spells that effect me.
also can you confirm that dot damage now shows correctly please

**Comment by sKlat-beep** [comment]
Attached a screenshot of my settings, I've tried different combinations of best guess/effect me only as well as the class only stuff- still doesn't seem to work when I cast on others, it just flashes their name for a second and disappears.

![Screenshot 2023-10-14 121638](https://github.com/smasherprog/EqTool/assets/61855386/13026fa0-f1ea-4aca-9388-50679f27baad)

DoT Damage seems to be good though!! Thank you again for taking the time to update this, especially since you're not playing on Quarm.

**Comment by smasherprog** [comment]
Very interesting. Thanks for the pic it does help.

I'll check this out.

**Comment by smasherprog** [comment]
Try checking best guess.

**Comment by smasherprog** [comment]
That checkbox is poorly named btw

**Comment by sKlat-beep** [comment]
For sure, I've tried it with Best guess off and on, combo'd with Effect me off and on

**Comment by smasherprog** [comment]
I AM able to reproduce the buff bugg.. trying to fix that now

**Comment by smasherprog** [comment]
FIX is live now your program should auto update and start working as expected!
