### ISSUE TITLE
Butcherblock Death Timers

### ISSUE THREAD

**Issue by LupahZ** [smasherprog/EqTool#44]
Death Timers are all off in BBM

Everything seems to be setting to 10 mins.  Zone timer is 15 Mins.  

Guards are on a 24m Timer

**Comment by LupahZ** [comment]
Sorry let me add the actual suggestion.

So many mobs and so many different zones will be an issues to find the right timer for every mob.  

What if all mob timers are based off the zone timer on the wiki.  If any other mobs are on a different timer, could we get the ability to right click the death timer on that mob, and "change respawn timer" option.  Then we place the new time in and next time it dies it starts the death timer with the modifited number.

**Comment by smasherprog** [comment]
Put the list here of what needs to change and ill update it

**Comment by smasherprog** [comment]
All mobs are based on the zone timer in the wiki, then i have a list of custom timers for individuals that dont follow the zone timer.

**Comment by LupahZ** [comment]
Zone Timer: 15 Mins (currently its doing 10 mins)

All Guards : 24 Mins

Nyzil Bloodforge:  6m 40s
Durkis Battlemore: 6m 40s
Walnan:  6m 40s

These are timers I know, and farm alot.

**Comment by smasherprog** [comment]
All guards in BB set to 24 minutes, and the above 3 added. Will be available in about 4 minutes

**Comment by smasherprog** [comment]
Going to close this ticket. If you find other mobs please post them and ill get it updated asap.
