### ISSUE TITLE
Random program restart

### ISSUE THREAD

**Issue by morgs71** [smasherprog/EqTool#47]
Multiple times throughout the day the program will close all the windows and restart itself.  Have confirmed this is happening to multiple people.  Also when it does this the opacity settings revert to above all other windows so you have to launch settings windows and uncheck boxes.

**Comment by smasherprog** [comment]
Yeah thats my bad. it restarts when ever an update is applied and i do alot of updates.

The program wont auto update us there are MORE than 3 timers in the timers window  to try and check if the program is idle. 

Ill add better idle checks before applying updates

**Comment by smasherprog** [comment]
Update heading out now to change the behavior for auto update to only update if you have been idle for at least 2 minutes

**Comment by smasherprog** [comment]
Gonna close this. Let me know if this resolves the issue. I can extend the 2 minute idle window to be 10 minutes if needed
