### ISSUE TITLE
Automatic ToD collection

### ISSUE THREAD

**Issue by morgs71** [smasherprog/EqTool#49]
Since the awesome map update with player locations it means that the program is capable of collecting data and sharing it as a whole with other users.  Would it be possible to take certain time of deaths such as scout/angry goblin and such and make it record and update a possible new window so all users get the ToDs of server spawns?  Possibly even make it so users can type in text in a certain format so the program can alert others to possible factions pulls and such example: Kael faction pull xx:42 which would start a timer in new window and alert others

**Comment by smasherprog** [comment]
Updated heading out now  with trashcans next to EACH of these so these can be removed.

**Comment by smasherprog** [comment]
This should be live now
