### ISSUE TITLE
Triggers/Timers grey unknown timers since latest update.

### ISSUE THREAD

**Issue by TheAngryRogue** [smasherprog/EqTool#51]
![unknownerror](https://github.com/smasherprog/EqTool/assets/48821225/c0d5395b-fb1e-4cdc-8a7a-d1389e07fe76)

Some buffs are now coming up as grey bars with no timer, name or green active timer section.

**Comment by GoofyWarriorGuy** [comment]
I think this is effects from other classes. So if you normally only select your own spells or spells from your own class then these are normally hidden. But after last patch they appear as a bar but have no name.

**Comment by smasherprog** [comment]
ill take a look later today
