### ISSUE TITLE
Primal Essence

### ISSUE THREAD

**Issue by LupahZ** [smasherprog/EqTool#58]
Primal Essence from Hammer of the Dragonborn is not loading the buff timer when I cast on my pet.
Its working on all other PC's but i tried with a few different pets and it never seems to start a timer.

**Comment by smasherprog** [comment]
ill check it out

**Comment by smasherprog** [comment]
can you send logs of the events that work and  dont work? Along with a screen shot of your settings page

**Comment by LupahZ** [comment]
![image](https://github.com/smasherprog/EqTool/assets/127626712/17455bc1-dabd-42f9-8f22-d2baa760aba6)

[Thu Dec 07 06:11:31 2023] You have healed Zenann for 405 points of damage.
[Thu Dec 07 06:11:31 2023] Zenann looks focused.
[Thu Dec 07 06:11:35 2023] You begin casting Focus of Spirit.
[Thu Dec 07 06:11:42 2023] an off duty Researcher begins to cast a spell.
[Thu Dec 07 06:11:48 2023] an off duty Researcher begins to cast a spell.
[Thu Dec 07 06:11:48 2023] Your focus fades.
[Thu Dec 07 06:11:48 2023] You feel focused.
[Thu Dec 07 06:11:52 2023] an off duty Accountant begins to cast a spell.
[Thu Dec 07 06:12:01 2023] You begin casting Primal Essence.
[Thu Dec 07 06:12:01 2023] Your Hammer of the Dragonborn begins to glow.
[Thu Dec 07 06:12:02 2023] an off duty Accountant begins to cast a spell.
[Thu Dec 07 06:12:03 2023] Your spell is interrupted.
[Thu Dec 07 06:12:05 2023] You begin casting Primal Essence.
[Thu Dec 07 06:12:05 2023] Your Hammer of the Dragonborn begins to glow.
[Thu Dec 07 06:12:15 2023] Your primal essence fades.
[Thu Dec 07 06:12:15 2023] You feel primeval.
[Thu Dec 07 06:12:17 2023] You begin casting Primal Essence.
[Thu Dec 07 06:12:17 2023] Your Hammer of the Dragonborn begins to glow.
[Thu Dec 07 06:12:22 2023] an off duty Scribe begins to cast a spell.
[Thu Dec 07 06:12:27 2023] Zenann shines with a primal aura.
[Thu Dec 07 06:12:30 2023] an off duty Accountant begins to cast a spell.
[Thu Dec 07 06:12:41 2023] an off duty Scribe begins to cast a spell.
[Thu Dec 07 06:12:42 2023] an off duty Researcher begins to cast a spell.

**Comment by smasherprog** [comment]
Thanks for that fix is on its way now. Will be available in about 5 minutes. Let me know if this works

**Comment by smasherprog** [comment]
Gonna close this let me know if its STILL broke
