### ISSUE TITLE
PQTool Death Flags on Map Issues

### ISSUE THREAD

**Issue by daeo** [smasherprog/EqTool#62]
I noticed while using the Map tool that if I have entered a zone death flags will be super small as the map zoom will reset.  I don't have the map super huge, typically the size of a photo ID card on 1600x900 resolution.  I'll have some screenshots once I have some examples, but the change I would suggest would be to lock scale of those death markers to match the zoom/scale of the map at the time it was created so that if/when you zone and the map size is reset, the death flags will be of a similar scale prior to the zone so that a rescale/zoom in the window results in flags that can be seen rather than ending up being tiny dots.

**Comment by smasherprog** [comment]
closing this as i dont support quarm any more
