### ISSUE TITLE
Mob respawn times on Quarm

### ISSUE THREAD

**Issue by gabbermatt** [smasherprog/EqTool#65]
So the timers for Project Quarm are (for the most part) 8 minutes, but all the timers on the map kill timers are set to 28 minutes.

Would it be possible to either change the default to 8 or let us do custom timers by right clicking on the timer in the map?

**Comment by smasherprog** [comment]
You can add all of the zone timers here 
https://github.com/smasherprog/EqTool/blob/28de66f80d055d7c87e23e253413269834745527/EQToolShared/Map/ZoneParser.cs#L1403
Issue a pull request with the timers that you know of. Ill approve it and it will be available about 5 minutes afterwards.
Its simple to add it so everyone can benefit!

**Comment by smasherprog** [comment]
ZoneInfoMap["unrest"].RespawnTime = new TimeSpan(0, 8, 0);

The string is the short name of the map you can find in the same file. TimesSpan(HOURS, MINUTES, SECONDS)

So even if you have never written code, you can do it!
I look forward to your pull request!

**Comment by smasherprog** [comment]
Closing since there is no traction on this
