### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by hobbythewise** [smasherprog/EqTool#77]
Can't force EQtools to load - icon appears in my icons tray but can't right click to open map or anything. Have forced-closed. Issue started today 12/28.

**Comment by smasherprog** [comment]
Is this ongoing?
Is this the P99 version of the PQ version?

**Comment by hobbythewise** [comment]
Yes. P99 - has been ongoing all day.

**Comment by smasherprog** [comment]
If you can see if theres any error.txt file and send that to me 
also your settings file as well
<img width="748" alt="image" src="https://github.com/smasherprog/EqTool/assets/3393733/08577db5-ada8-4c2d-ada6-5897e6b361b1">

If you dont want to post if here send it to me over discord   my handle is smasherprog#0531

**Comment by hobbythewise** [comment]
My errors.text file hasn't been updated / altered since 11/26/23 -- i'll copy/paste Settings.json:

{
  "DefaultEqDirectory": "E:\\Everquest",
  "EqLogDirectory": "E:\\Everquest\\Logs",
  "FontSize": 12,
  "SpellWindowState": {
    "WindowRect": "281,11,336,450",
    "State": 0,
    "Closed": true,
    "AlwaysOnTop": false,
    "Opacity": 1.0
  },
  "DpsWindowState": {
    "WindowRect": "21,557,640,271",
    "State": 0,
    "Closed": true,
    "AlwaysOnTop": false,
    "Opacity": 1.0
  },
  "MapWindowState": {
    "WindowRect": "1255,592,640,450",
    "State": 0,
    "Closed": false,
    "AlwaysOnTop": false,
    "Opacity": 1.0
  },
  "MobWindowState": {
    "WindowRect": "78,78,562,333",
    "State": 0,
    "Closed": true,
    "AlwaysOnTop": false,
    "Opacity": 1.0
  },
  "Players": [
    {
      "Level": 60,
      "BestPlayerDamage": {
        "TargetTotalDamage": 160,
        "HighestDPS": 13,
        "HighestHit": 160
      },
      "Name": ,
      "TrackingSkill": 
      "GuildName": 
      "Zone": "commons",
      "MapLocationSharing": 0,
      "MapKillTimers": true,
      "PlayerClass": 5,
      "TrackingDistance": 2500.0,
      "IsTrackableClass": true,
      "Server": 0,
      "YouSpells": [
        {
          "Name": "Gift of Brilliance",
          "TotalSecondsLeft": 1007
        },
        {
          "Name": "Spirit of Ox",
          "TotalSecondsLeft": 980
        },
        {
          "Name": "Protection of the Glades",
          "TotalSecondsLeft": 5696
        }
      ],
      "ShowSpellsForClasses": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13
      ]
    }
  ],
  "BestGuessSpells": true,
  "YouOnlySpells": false
}

**Comment by hobbythewise** [comment]
I re-downloaded .zip from git and extracted / replaced the existing eqtools file as well. Also restarted pc.

**Comment by hobbythewise** [comment]
[Errors.txt](https://github.com/smasherprog/EqTool/files/13790402/Errors.txt)

**Comment by hobbythewise** [comment]
When extracting an older downloaded version, it lets me right click it -- but the auto-update immediately closes it and re-launches the icon which breaks again.

**Comment by hobbythewise** [comment]
Update: By moving the EQTools exe out of the main EQ folder and into some random folder (placed it into Logs simply because it was the most recent used folder) -- the program has started working.

A few days ago I did the DGVoodo but EQTools has worked since that process so I am unsure what changed. Program worked on Wednesday, stopped Thursday, working today by changing folders.

**Comment by smasherprog** [comment]
What was the folder path?

**Comment by hobbythewise** [comment]
E:\Everquest 

Moved to E:\Everquest\Logs and program began working again.

**Comment by smasherprog** [comment]
I do intend on checking this out at some point to see why running from the eq directory would causes issues...

**Comment by smasherprog** [comment]
Thanks for reporting it!
