### ISSUE TITLE
BBM Guard Missed Timers

### ISSUE THREAD

**Issue by LupahZ** [smasherprog/EqTool#78]
Butcher Block Mountains

Guard Dunil
Guard Clendin

Both these guards are still on the 6m40s timer.  They need to be updated to a 24m timer.  Thank you!

**Comment by iSteed** [comment]
From what i can tell, all the database information is pulled from the project 1999 wiki.  so as long as things are updated on https://wiki.project1999.com/Guard_Dunil things should line up in the app.

**Comment by smasherprog** [comment]
thanks for the PR. changes merged! They will be available soon
