### ISSUE TITLE
Suggestion: Invis / Lev Falling off warning

### ISSUE THREAD

**Issue by daeo** [smasherprog/EqTool#80]
Since we don't have audio queues, maybe an option to add an audio queue for these kinds of events?

**Comment by smasherprog** [comment]
good idea! ill add this soon

**Comment by smasherprog** [comment]
Audio and visual alerts added to the program. Give it a shot

**Comment by daeo** [comment]
Thanks for your work! Its working out great for invis and lev warnings!
