### ISSUE TITLE
Druid Epic Trigger

### ISSUE THREAD

**Issue by hobbythewise** [smasherprog/EqTool#81]
Natures Wrath isnt getting tracked on triggers if I cast Flame Lick first. 

Flame lick will trigger - then I will click epic but no entry despite landing.

Flame lick lands
Dronse of doom lands
Natures wrath lands --- this cycle will trigger each entry.

Flame lick lands
Nature wraths lands (no entry)
Drones of doom lands (entry).

Casting time varies between immediately after flamelick lands, to waiting for spell gems to re-pop and no entry on first epic spell.

If cast time is over 4 seconds delay between flame lick, nature will trigger. 

Howeever, this delay is not required for Drones of Doom casting.

**Comment by smasherprog** [comment]
ill have to test this out on a druid. Can you send me logs of this? If you send me  the log entries i can replay it without needing to log into a druid

**Comment by hobbythewise** [comment]
The first two goblins (unbolded) did not trigger the epic spell.
The last goblin (bolded) did. I changed the order to be DoD first.


Thu Jan 04 08:20:03 2024] fire goblin says, 'Die by lava - Die by flame - Fire Peak goblins kill and maim.'
[Thu Jan 04 08:20:03 2024] flame goblin says, 'Die by lava - Die by flame - Fire Peak goblins kill and maim.'
[Thu Jan 04 08:20:03 2024] blazing elemental begins to cast a spell.
[Thu Jan 04 08:20:04 2024] Fire goblin bashes YOU for 12 points of damage.
[Thu Jan 04 08:20:04 2024] Fire goblin hits YOU for 52 points of damage.
[Thu Jan 04 08:20:05 2024] Flame goblin bashes YOU for 2 points of damage.
[Thu Jan 04 08:20:05 2024] Flame goblin hits YOU for 2 points of damage.
[Thu Jan 04 08:20:06 2024] You begin casting Engorging Roots.
[Thu Jan 04 08:20:07 2024] Fire goblin tries to hit YOU, but misses!
[Thu Jan 04 08:20:07 2024] blazing elemental begins to cast a spell.
[Thu Jan 04 08:20:07 2024] fire goblin was hit by non-melee for 190 points of damage.
[Thu Jan 04 08:20:07 2024] Fire goblin's feet become entangled.
[Thu Jan 04 08:20:08 2024] Flame goblin tries to hit YOU, but misses!
[Thu Jan 04 08:20:09 2024] You haven't recovered yet...
[Thu Jan 04 08:20:10 2024] You begin casting Engorging Roots.
[Thu Jan 04 08:20:11 2024] Flame goblin tries to hit YOU, but misses!
[Thu Jan 04 08:20:11 2024] Flame goblin tries to hit YOU, but misses!
[Thu Jan 04 08:20:12 2024] flame goblin was hit by non-melee for 190 points of damage.
[Thu Jan 04 08:20:12 2024] Flame goblin's feet become entangled.
[Thu Jan 04 08:20:13 2024] Flame goblin tries to bash YOU, but misses!
[Thu Jan 04 08:20:14 2024] You begin casting Wrath of Nature.
[Thu Jan 04 08:20:14 2024] Your Nature Walkers Scimitar begins to glow.
[Thu Jan 04 08:20:23 2024] Flame goblin has been gripped by nature's wrath.
[Thu Jan 04 08:20:25 2024] You begin casting Drones of Doom.
[Thu Jan 04 08:20:25 2024] Your Woven Grass Bracelet begins to glow.
[Thu Jan 04 08:20:28 2024] gnomish conjurer begins to cast a spell.
[Thu Jan 04 08:20:32 2024] Flame goblin is engulfed in a swarm.
[Thu Jan 04 08:20:34 2024] You begin casting Wrath of Nature.
[Thu Jan 04 08:20:34 2024] Your Nature Walkers Scimitar begins to glow.
[Thu Jan 04 08:20:39 2024] gnomish conjurer begins to cast a spell.
[Thu Jan 04 08:20:43 2024] Fire goblin has been gripped by nature's wrath.
[Thu Jan 04 08:20:44 2024] You begin casting Drones of Doom.
[Thu Jan 04 08:20:44 2024] Your Woven Grass Bracelet begins to glow.
[Thu Jan 04 08:20:45 2024] fire goblin shaman begins to cast a spell.
[Thu Jan 04 08:20:51 2024] Fire goblin is engulfed in a swarm.
[Thu Jan 04 08:20:55 2024] gnomish conjurer begins to cast a spell.
[Thu Jan 04 08:21:02 2024] gnomish curator begins to cast a spell.
[Thu Jan 04 08:21:07 2024] You have slain flame goblin!
[Thu Jan 04 08:21:07 2024] Your faction standing with GoblinsofFirePeak could not possibly get any worse.
[Thu Jan 04 08:21:16 2024] fire goblin wizard begins to cast a spell.
[Thu Jan 04 08:21:27 2024] blazing elemental begins to cast a spell.
[Thu Jan 04 08:21:28 2024] You have slain fire goblin!
[Thu Jan 04 08:21:28 2024] Your faction standing with GoblinsofFirePeak could not possibly get any worse.
[Thu Jan 04 08:21:30 2024] gnomish conjurer begins to cast a spell.
[Thu Jan 04 08:21:39 2024] fire goblin shaman begins to cast a spell.
[Thu Jan 04 08:21:45 2024] blazing elemental begins to cast a spell.
[Thu Jan 04 08:21:56 2024] blazing elemental begins to cast a spell.
[Thu Jan 04 08:22:03 2024] fire goblin wizard begins to cast a spell.
[Thu Jan 04 08:22:04 2024] gnomish conjurer begins to cast a spell.
[Thu Jan 04 08:22:10 2024] You begin casting Engorging Roots.
[Thu Jan 04 08:22:11 2024] flame goblin wizard begins to cast a spell.
**[Thu Jan 04 08:22:12 2024] You regain your concentration and continue your casting.
[Thu Jan 04 08:22:12 2024] fire goblin says, 'Die by lava - Die by flame - Fire Peak goblins kill and maim.'
[Thu Jan 04 08:22:12 2024] fire goblin was hit by non-melee for 190 points of damage.
[Thu Jan 04 08:22:12 2024] Fire goblin's feet become entangled.
[Thu Jan 04 08:22:12 2024] You begin casting Drones of Doom.
[Thu Jan 04 08:22:12 2024] Your Woven Grass Bracelet begins to glow.
[Thu Jan 04 08:22:20 2024] Fire goblin is engulfed in a swarm.
[Thu Jan 04 08:22:20 2024] You begin casting Wrath of Nature.
[Thu Jan 04 08:22:20 2024] Your Nature Walkers Scimitar begins to glow.
[Thu Jan 04 08:22:30 2024] Fire goblin has been gripped by nature's wrath.**

**Comment by smasherprog** [comment]
perfect thanks for this i can reply it on my computer!

**Comment by smasherprog** [comment]
Thanks for this log file i was able to fix it. Will be heading out tonight

**Comment by smasherprog** [comment]
Fix is on its way now thanks for the info
