### ISSUE TITLE
forced window on top

### ISSUE THREAD

**Issue by ikiris** [smasherprog/EqTool#82]
Some of us use multiple monitors and forced on top is *not* a positive change.

**Comment by morgs71** [comment]
Please let us choose i can't use a browser on my 2nd window to look at wiki now

**Comment by smasherprog** [comment]
illl add it back tomorrow

**Comment by smasherprog** [comment]
<img src="https://media4.giphy.com/media/l1J9u3TZfpmeDLkD6/200w.gif"/>

**Comment by smasherprog** [comment]
at work still ill be home soon. If i am home early enough ill add this, otherwise it will have to wait till tomorrow

**Comment by smasherprog** [comment]
Code done will be heading out soon

**Comment by smasherprog** [comment]
Fix is on its way now will be out in a few minutes
