### ISSUE TITLE
Items not appearing on website after recent update

### ISSUE THREAD

**Issue by WigF1** [smasherprog/EqTool#86]
Items are not appearing in results when they should be.

Here is a search for Earring of Woven Bark
![image](https://github.com/smasherprog/EqTool/assets/12164329/9405a98e-42c5-4ac5-b2af-3fc7f842f285)

Notice the 'last seen', now compare that to clicking on the item (https://pigparse.azurewebsites.net/ItemDetails/15690)

Sorting into Descending shows 28/12 as the most recent result
![image](https://github.com/smasherprog/EqTool/assets/12164329/e7085580-be2b-492a-bbfa-d73b123b9352)

The item is actively being sold in the tunnel.

**Comment by smasherprog** [comment]
Thanks for pointing this out. The fix is heading out now.
