### ISSUE TITLE
Add mob mr/cr/fr to the con tool Mob Info window

### ISSUE THREAD

**Issue by Celedh** [smasherprog/EqTool#89]
Add mob mr/cr/fr to the con tool Mob Info window

**Comment by smasherprog** [comment]
This is something that would be available for PQ players. I dont play on PQ, but if someone wants to jump in and do some work to support these things for PQ!, im all game. 
If that doesnt happen then this is likely never going to get done.

**Comment by smasherprog** [comment]
Gonna close this unless i get someone who wants to contribute and plays PQ. I dont play on PQ and have added basic support for it, but thats about as far as I have time to do.
