### ISSUE TITLE
creating an msi installer for EqTool

### ISSUE THREAD

**Issue by sinapis-amicus** [smasherprog/EqTool#9]
Would it be unnecessary to have an installer this early in development?

This may be something people would be interested in.

**Comment by smasherprog** [comment]
Yeah, its a good idea for sure! I am going to purchase a code signing certificate soon so you dont get that stupid warning when launching the executable.

I think maybe a single exe would be a good idea instead? For example, if the file that is downloaded is a single exe that you simply run and there are no other files would that work too?

Lets discuss what ever gives users the easiest/fastest experience. 

I was planning on bundling everything into a single executable so users only download a single file and simply run it. Do you think this is a good idea, or do you think the msi installer is a better idea and why?

**Comment by sinapis-amicus** [comment]
> Yeah, its a good idea for sure! I am going to purchase a code signing certificate soon so you dont get that stupid warning when launching the executable.
> 
> I think maybe a single exe would be a good idea instead? For example, if the file that is downloaded is a single exe that you simply run and there are no other files would that work too?
> 
> Lets discuss what ever gives users the easiest/fastest experience.
> 
> I was planning on bundling everything into a single executable so users only download a single file and simply run it. Do you think this is a good idea, or do you think the msi installer is a better idea and why?

I do think the single executable is preferable because it's the quickest, simplest, download and click.
The only benefit I see in an installer is that it's a little more standard and can be added to [Winget](https://github.com/microsoft/winget-cli) (the windows package manager).

**Comment by smasherprog** [comment]
This is the guide I was going to use to bundle everything together. It seems very straightforward
http://www.digitallycreated.net/Blog/61/combining-multiple-assemblies-into-a-single-exe-for-a-wpf-application

**Comment by smasherprog** [comment]
If you wana give a shot at doing the single exe, that would be awesome!  I like PR's

**Comment by smasherprog** [comment]
I am working on the above right now..FYI

**Comment by smasherprog** [comment]
Just completed the work to collapse the file needed into a single exe.  Once ran it does spit out 3 files, but its a Download and run now with no need for unziping

**Comment by smasherprog** [comment]
Now i just need to get the exe signed to help with anti virus and those warnings that always pop up
