### ISSUE TITLE
Guard Chopin Spawn Time

### ISSUE THREAD

**Issue by mktpratt** [smasherprog/EqTool#91]
Very small request, but hoping to add a NpcSpawnTime for Guard Chopin in Highkeep for 3:00. I see the custom setups for Blayle, Boshinko, Isabella and the Nobles but no Chopin.

https://wiki.project1999.com/Guard_Chopin

**Comment by smasherprog** [comment]
Added. WIll be available via updates in about 5 minutes. Let me know if this doesnt work

**Comment by smasherprog** [comment]
Update available now!

**Comment by mktpratt** [comment]
Confirmed working. Appreciate the quick turnaround!
