### ISSUE TITLE
a suit of sentient armor timer is wrong

### ISSUE THREAD

**Issue by shenthewise** [smasherprog/EqTool#94]
correct respawn timer is 14:30m
currently eqtool shows 6m

https://wiki.project1999.com/A_suit_of_sentient_armor

**Comment by smasherprog** [comment]
Can you give me a slain message from logs?
The code looks correct so there something missing here

**Comment by smasherprog** [comment]
Can you find anything for me on this? it should be correct in the program..

**Comment by smasherprog** [comment]
gonna close this until more info is added
