### ISSUE TITLE
Kill Timers to update

### ISSUE THREAD

**Issue by Kritoris** [smasherprog/EqTool#96]
Hi, I went through and have identified some more names that are not on their correct timers. I am not sure if/how you might handle windows but I threw Vindi in there just to be difficult...

Not sure if this is easy enough for you to work with or I can throw something in Google Drive to access form a CSV?

Zone	Named	Time Span
warrens	King Gragnar	(0, 48, 0)
warrens	High Shaman Drogik	(0, 48, 0)
warrens	Lorekeeper Roggik	(0, 48, 0)
warrens	Trainer Daxgrr	(0, 20, 0)
warrens	Cave Bat Lord	(0, 48, 0)
warrens	Foodmaster Rargnar	(0, 20, 0)
warrens	Huntmaster Furgrl	(0, 48, 0)
warrens	The Muglwump	(0, 35, 0)
warrens	Packmaster Dledsh	(0, 16, 0)
warrens	Prince Bragnar	(0, 57, 0)
warrens	Smithy Rrarrgin	(0, 20, 0)
warrens	Warlord Drrig	(0, 13, 0)
westwastes	Amcilla	(8, 30, 0)
westwastes	Atpaev	(8, 30, 0)
westwastes	Bufa	(8, 30, 0)
westwastes	Crial	(8, 30, 0)
westwastes	Gangel	(8, 30, 0)
westwastes	Honvar	(8, 30, 0)
westwastes	Linbrak	(8, 30, 0)
westwastes	Makala	(8, 30, 0)
westwastes	Myga	(8, 30, 0)
westwastes	Nintal	(8, 30, 0)
westwastes	Onava	(8, 30, 0)
westwastes	Quoza	(8, 30, 0)
westwastes	Sivar	(8, 30, 0)
westwastes	Uiliak	(8, 30, 0)
westwastes	Yal	(8, 30, 0)
westwastes	Ayillish	(8, 0, 0)
westwastes	Derasinel	(8, 0, 0)
westwastes	Draazak	(8, 0, 0)
westwastes	Entariz	(8, 0, 0)
westwastes	Harla Dar	(8, 0, 0)
westwastes	Ionat	(8, 0, 0)
westwastes	Jen Sapara	(8, 0, 0)
westwastes	Kar Sapara	(8, 0, 0)
westwastes	Karkona	(8, 0, 0)
westwastes	Lord Gossimerwind	(0, 6, 40)
westwastes	A Faerie Dragon	(0, 6, 40)
Kael	Derakor the Vindicator	(7, 0, 0) to (9, 0, 0)
Kael	Keldor Dek`Torek	(18, 0, 0)

lakeofillomen	Chancellor of Di`Zok	(2, 0, 0)

charasis	Drusella Sathir	(24, 0, 0)
oot	Gull Skytalon	(8, 0, 0)
oot	Guardian of K`Arnon	(0, 22, 0)
highpass	Hagnis Shralok	(0, 22, 0)
highpass	Recfek Shralok	(0, 22, 0)
highpass	Vopuk Shralok	(0, 22, 0)
highpass	Vexven Mucktail	(0, 22, 0)
highpass	Grenix Mucktail	(0, 22, 0)
qcat	A Spectre	(0, 24, 0)
paw	The Ishva Mal	(0, 28, 0)
paw	An Ishva Lteth gnoll	(0, 28, 0)

**Comment by morgs71** [comment]
fake flurries in the pits of NToV may be off too

**Comment by smasherprog** [comment]
Do you think there's value in the long spawns showing in the program?

**Comment by smasherprog** [comment]
like the 8 hour and more spawns?

**Comment by Kritoris** [comment]
I know I leave my PC running for weeks at a time before I bother to reboot, or if I won't be using it for a decent period.  

So I think those Mid-term ones definitely. Eg 6 Neck Dragons and Myga spawn cycle are very attractive targets for people they will want to track.

The 8+ hour with windows are worth it. Even 3 days spawns would probably be worth it. 5 and 7? Maybe less so.

People often kill Vindi before they go to bed and are awake for his windows the next morning.

**Comment by smasherprog** [comment]
> fake flurries in the pits of NToV may be off too

They are for sure off. I am not sure what the respawn timers are on the guards/flurries/fake flurries

**Comment by smasherprog** [comment]
all of these have been added to the update that will go out today

**Comment by smasherprog** [comment]
Code pushed should be live in about 5 minutes
