### ISSUE TITLE
CH chain feature

### ISSUE THREAD

**Issue by morgs71** [smasherprog/EqTool#97]
Hey would it be possible to add two extra fields in the ini for time (time in between casts possibly change on fly) and your position in the chain.  This would possibly allow the program to give a audio/visual alert of when its time to cast your ch spell. (I don't play cleric but the usual complaint is people not keeping the timing)

**Comment by smasherprog** [comment]
I think this is a good idea.
But i think that i can figure out your position in the CH chain and do this automatically. As for the audio/visual warning, I think I can do the warning when the person in front of you goes

So, here is how it would go.

A normal chain is always ran before engage and/or it is setup before engage. From this i can figure out what spot you are in the chain automatically

When the person in front of you goes, i can have an audio/visual warning at that time as normal chains are 1-4 seconds this will give you time.

I like things that are automatic and that just work without users having to do anything.
Now, if people drop out or die, there isnt anything i can do. At some point people just need to pay attention.
But for the happy path, i can automate it..

Thoughts?

**Comment by morgs71** [comment]
Sounds good to me bud you know I play a rogue so this is just to help others keep up timing in a chain and to avoid misses hopefully.  Thank you !

**Comment by smasherprog** [comment]
Just added support for this. All thats needed is a simple checkbox in the settings and it will work. I marked it as experimental since i just added support for it.

**Comment by smasherprog** [comment]
Gonna close this as support has been added. Please post another issue with any improvements that you can think of
