### ISSUE TITLE
guard oystind

### ISSUE THREAD

**Issue by shenthewise** [smasherprog/EqTool#98]
For some reason, guard oystind in north karana never shows up in the triggers list after he is killed

**Comment by smasherprog** [comment]
Dig up slain message from logs please and post here

**Comment by smasherprog** [comment]
my guess is that you were not close enough to see the slain message in logs. This must be present otherwise TOD cant be added automatically.. If you kill and dont see the TOD, try using the manual process: type

start timer guard oystind 7

Without further information im gonna close this. Please post if you find anything additional to add

**Comment by shenthewise** [comment]
It definitely happens at close range. I tried dozens of times.
Other guards around him trigger the timer just fine. Hmmm

Pasting relevant log entries below.


[Tue Jan 23 20:48:26 2024] Your Envenomed Breath spell has worn off.
[Tue Jan 23 20:48:27 2024] You try to crush Guard Oystind, but miss!
[Tue Jan 23 20:48:29 2024] Guard Oystind slashes YOU for 7 points of damage.
[Tue Jan 23 20:48:29 2024] Guard Oystind tries to slash YOU, but misses!
[Tue Jan 23 20:48:29 2024] You crush Guard Oystind for 8 points of damage.
[Tue Jan 23 20:48:31 2024] You crush Guard Oystind for 39 points of damage.
[Tue Jan 23 20:48:32 2024] Guard Oystind slashes YOU for 7 points of damage.
[Tue Jan 23 20:48:33 2024] You crush Guard Oystind for 35 points of damage.
[Tue Jan 23 20:48:33 2024] You have slain Guard Oystind!
[Tue Jan 23 20:48:33 2024] Your faction standing with AntoniusBayle could not possibly get any worse.
[Tue Jan 23 20:48:33 2024] Your faction standing with CircleofUnseenHands could not possibly get any better.
[Tue Jan 23 20:48:33 2024] Your faction standing with CorruptQeynosGuards got better.
[Tue Jan 23 20:48:33 2024] Your faction standing with GuardsofQeynos could not possibly get any worse.
[Tue Jan 23 20:48:33 2024] Your faction standing with MerchantsofQeynos could not possibly get any worse.
[Tue Jan 23 20:48:33 2024] You gain experience!!

**Comment by smasherprog** [comment]
Thanks for the logs. I did find a bug where dead timers werent working in some scenarios. I fixed it on the 21 i think. Please let me know if this issue still persists.
